### PR TITLE
add more tests

### PR DESCRIPTION
**Pull request by melnikaite**

### CODE REVIEW

**Comment by jeremyevans** [comment]
First, thank you for submitting a pull request.  Most of the changes you made are good, however, I think some changes need to be made before this can be merged:

.ruby-gemset, .ruby-version, r.txt, and r.csv should not be committed.

I think Gemfile.lock is always inappropriate to commit for libraries. It's only for applications, and even then I think it should only be used for testing->staging->deployment scenarios.  Granted, that's not a popular opinion among ruby developers.  My main problem with Gemfile.lock is it encourages a myopic view of dependencies, when in general code should work with as wide a range of dependency versions as possible.  Any code that depends on exact dependency versions could be correctly described as brittle.

In this particular case, I don't think Gemfile is appropriate either.  While I don't have a problem with simple_orm_benchmarker supporting mongoid, I don't think we should be pushing users to install it (friends don't let friends use MongoDB).  Likewise, if my database is PostgreSQL and I'm using simple_orm_benchmarker to see the difference between ActiveRecord and Sequel, I shouldn't be pushed to install mysql2 and sqlite3.

I don't think it is appropriate to add support for json functions on SQLite, until such support is enabled by default in SQLite.  If you really want to test json support on SQLite, you can use amalgalite, which is a ruby gem that bundles SQLite and enables the json extension in it.  Related to this, the dylib and enable_load_extension code can be removed as well.  I'm not sure if ActiveRecord supports amalgalite, but I know Sequel does.

To keep db.yml.example DRY, we should also default to transactional: true and debug: false, and only have a transactional: false entry for mongoid.

I don't think it's appropriate to integrate json handling with the existing benchmarks. The database should be tested for json format, and only if json is supported, then add a separate model with a json column and run the related benchmarks.

**Comment by melnikaite** [comment]
Thanks for quick response

I agree with you that Gemfile, Gemfile.lock, .ruby-gemset, .ruby-version, r.txt, and r.csv should not be committed, I'd just keep Gemfile.example. I did it only for those people who don't want to run benchmark, but just want to do see results and know if used versions of software are not too old to be taken seriously. How we can help those people in different way?

Thanks for mentioning amalgalite, I looks better than installing SQLite separately and enabling features manually or in code. I'd update my PR with this gem, but unfortunately only sequel has up to date adapter, activerecord-amalgalite-adapter is extremely outdated.

**Comment by jeremyevans** [comment]
These new changes have improved things, thanks!

We can get rid of `Gemfile.example`, and remove the `Gemfile*`,  `.ruby*`, and `r.csv` entries from the `.gitignore` file.  The `r.txt` can stay since that is what the example in the README shows.  

I think the README changes can be reverted.  For one thing, the README states that the command will output CSV, and with the redirection, that is no longer the case.

I specifically chose not to include benchmark results as part of the repository. If people want to see benchmark results, I encourage them to run the benchmark themselves.  They are free to post the results of the benchmark on their own site/blog and update their social media with a link to it.  We help people by providing the benchmark software, the rest is on them.

If only Sequel has recent support for amalgalite, then you could only add a db.yml.example entry for amalgalite and Sequel and not for amalgalite and ActiveRecord.  Alternatively, you could just skip the JSON benchmarks completely on SQLite.  As I mentioned, the JSON benchmarks should be separate, not integrated into the existing benchmarks.

**Comment by jeremyevans** [comment]
These changes are looking good.  The dylib/enable_load_extension code still needs to be removed, and the JSON benchmarks separated from the existing benchmarks, but other than that it should be mostly ready for merging.

**Comment by melnikaite** [comment]
Unfortunately dylib/enable_load_extension code still required for activerecord-sqlite and JSON benchmarks was the main idea of my investigation. May be we can add functionality to select what tests should be run? In this case user won't have to do custom sqlite installation.

**Comment by jeremyevans** [comment]
I explained above that then you should just not run the JSON benchmarks on ActiveRecord since the default SQLite installation does not support them.  Alternatively, you could look into fixing the ActiveRecord amalgalite adapter, though that is probably more work.  I will not accept code that uses enable_load_extension, especially with hardcoded, Mac OS X specific paths.

One possible option is to just test to see if the SQLite being loaded supports JSON natively, and allow use of JSON in that case.  That way, if you want to benchmark the SQLite JSON support, you just have to compile an SQLite with it.

I'd certainly consider an option that would allow filtering benchmarks by a regexp.  But the JSON benchmarks definitely need to be separate, I don't want the existing benchmarks modified.

**Comment by melnikaite** [comment]
Ok, I see your point
I'll try to check if loaded SQLite supports JSON, because other solutions will take more time

**Comment by jeremyevans** [comment]
This just moves the enable_load_extension to a different place in the code.  The dylib/enable_load_extension changes are not acceptable, they should be removed.

You can use `connection.execute('select json("{}")')[0][0] == '{}' rescue false` to check if the database supports json on SQLite (where `connection` is the appropriate connection object).  You should not assume that json is supported on anything other than Mongo, you need to check the version in use or try a JSON query.  On PostgreSQL, that's probably version 9.3+ depending on the queries you are using, and I'm sure there is something similar on MySQL, though you probably need to test for actual support there due to the various forks.

**Comment by jeremyevans** [comment]
Thanks for continuing to work on this.

I'm not sure the README instructions in regards to SQLite JSON support are correct.  They imply that enabling the extension once implies it will always be loaded.  I don't think that's how SQLite's extension loading works. I believe SQLite loads the extension into the process memory, and it must be loaded every time, or it must be compiled into the SQLite library itself.  Did you try the instructions and confirm that they work?

There is still a dylib entry for amalgalite that should be deleted.

In the Sequel supports_json? method, you should use `case DB.database_type; when :sqlite; DB.get{function_name('{}')} == '{}'` and similar code.  You don't want to test on the adapter, Sequel supports multiple adapters for all of the common databases.  ActiveRecord generally only supports 1 adapter for each database type, so I don't think that's an issue there.

The main work still to do is separating the JSON tests, and leave the existing tests alone.

**Comment by melnikaite** [comment]
Thanks for found issues.

Instruction is correct. I did activation once and able to use JSON functions even after reboot.

Separating JSON tests sounds like different feature. Before doing it we should discuss possible ways to implement it and choose the best one. Let's do filtering tests in another PR.

**Comment by jeremyevans** [comment]
I think the README instructions are wrong.  I'm guessing the reason it works for you is because you are compiling an SQLite with JSON support (--with-json1), not because you are loading the extension module separately.  My guess is it would work without the enable_load_extension stuff.  I can find nothing in the SQLite documentation that talks about loadable extensions persisting across processes.  By default, extensions get unloaded when the database connection closes, and the only persistence you can get is persistence until the process exits.  See https://www.sqlite.org/loadext.html.

Separating JSON tests is not a different feature.  Currently, there are no JSON tests.  This pull request attempts to modify all existing tests to add tests for JSON.  Before acceptance, it needs to be changed so the existing tests are not modified, and any JSON-specific tests are added as separate tests.  The subject of the pull request is "add more tests", not "modify existing tests to include tests for JSON" :).

I agree that filtering tests can be done in a separate PR, after JSON tests have been added.

**Comment by melnikaite** [comment]
Compiling with flag `--with-json1` is not enough. I had to run `enable_load_extension` and `load_extension` to avoid error about undefined function. I saw this instruction and was surprised that JSON functions still works.

**Comment by jeremyevans** [comment]
Are you running with the SQLite you compiled with `--with-json1`, or is there another version of SQLite installed on your system that ruby-sqlite3 is compiled against?

In any case, the README instructions should be limited to just telling people that if they want to test JSON on SQLite, they need to have the JSON functions compiled into SQLite, which is not the default.  We don't need to explain how to do that, I think it's out of scope.

This is a minor issue anyway, I can always clean up the README myself when I merge this.  The important work still to do is adding separate JSON tests instead of modifying the existing tests.

**Comment by melnikaite** [comment]
I'm considering adding new option -j to enable json tests. What do you think?

**Comment by jeremyevans** [comment]
I think such an option could be considered later, as that would be part of the filtering support.

**Comment by melnikaite** [comment]
So,  I'm a bit confused. What should be done in this PR?

**Comment by jeremyevans** [comment]
If you want to add JSON benchmarks to this library, they need to be added as separate benchmarks, without modifying the existing benchmarks.  That means a separate table (json_parties?) and separate model for the JSON benchmarks. What you've currently done is modify the existing parties table to add a JSON column, and therefore modified all benchmarks that use it, which I don't think is acceptable.

**Comment by jeremyevans** [comment]
Thanks, this last commit is exactly what I was looking for.  Let me do some testing with it and hopefully I'll be able to merge it today.

**Comment by jeremyevans** [comment]
I squash merged your commit and added a refactoring commit, see 0db5f9e1d264ffb27b298c0edd64c151f8b5590b.  Thanks for your work on this, please let me know if you think we should make additional changes.

**Pull request closed without merging**
